### ISSUE TITLE
[Bug]: One Use Booster vertex light not despawning on time

### ISSUE THREAD

**Issue by Ob3vious** [CommunalHelper/AnonHelper#4]
### Before You Report

- [X] My mods and Everest install are up to date.
- [X] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Windows 11

### Bug Description

I was making a map that uses a noticeable darkness alpha and I wanted to use the One-Use Booster (Red). When entering the booster and flying off, the light remained in place, appearing as if air is emitting light, to then suddenly disappear as the entity destroys itself. This behavior appears very unintended and is very disturbing. The image includes a moment in time while traveling in the booster while the light is still present. Note that this light disappears a moment after Madeline exits the booster.
![image](https://github.com/CommunalHelper/AnonHelper/assets/66796184/afec2c41-5126-46b3-94a2-6a7d3d89205d)
I checked the source code and figured this happens because the VertexLight of the vanilla booster is not being affected until eventually DestroySelf takes care of it. The result of this is a light that sticks around with no visible source until it disappears after the booster does.

### Steps to Reproduce

- Set up a map with a noticeable darkness alpha. I used 0.2
- Place a One-Use Booster (Red)
- Load up the map and play it
- Observe the vertex light disappearing at a moment that doesn't appear intuitive to a player.

**Comment by bigkahuna443** [comment]
I'm sorry you were disturbed by this. Fixed with #6.
