### ISSUE TITLE
[Bug]: Cloud refills dont let you instant hyper bhop on the left side

### ISSUE THREAD

**Issue by ChaosPhrog** [CommunalHelper/AnonHelper#5]
### Before You Report

- [X] My mods and Everest install are up to date.
- [X] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Windows 11 FNA

### Bug Description

When you instant hyper with a cloud refill to the left side you (i think) dont get corrected onto the cloud, but you do when you do it on the right

### Steps to Reproduce

[https://streamable.com/e97704](url)

**Comment by bigkahuna443** [comment]
Hmm I think I can replicate this? Not sure exactly why it happens though, and I don't think it's something that can be safely changed unfortunately. The cloud placements took a lot of tweaking and I would be too afraid to mess with established maps to tweak them any more.
